#!/usr/bin/env python3
"""Builds the JS8 tables the firmware needs from the JS8Call sources.

    python tools/js8/gen_tables.py <js8call source dir>

The directory needs (from https://github.com/js8call/js8call):
    lib/ft8/bpdecode174.f90       parity-check matrix of the (174,87) LDPC code
    lib/ft8/ldpc_174_87_params.f90 generator matrix and column order
    jsc_map.cpp                   JSC compression dictionary (262144 words)

Writes:
    src/js8_ldpc.inc     Mn, Nm, row weights, column order and generator rows
    data/jsc_dict.bin    the dictionary: a uint32 offset (little endian) every
                         JSC_GROUP words, then the words NUL-terminated, in
                         index order (the firmware embeds it)

The LDPC tables and the dictionary are part of the JS8 protocol as JS8Call
defines it (GPLv3); see data/README.md.
"""
import os
import re
import struct
import sys

JSC_GROUP = 64


def fortran_data(src, name):
    m = re.search(r'data\s+' + name + r'\s*/(.*?)/', src, re.S | re.I)
    if not m:
        sys.exit('no data ' + name)
    body = re.sub(r'!.*', '', m.group(1)).replace('&', ' ')
    return [int(v) for v in re.findall(r'-?\d+', body)]


def main():
    base = sys.argv[1]
    root = os.path.join(os.path.dirname(__file__), '..', '..')
    bp = open(os.path.join(base, 'lib/ft8/bpdecode174.f90')).read()
    par = open(os.path.join(base, 'lib/ft8/ldpc_174_87_params.f90')).read()
    N, K, M = 174, 87, 87
    mn = fortran_data(bp, 'Mn')            # Mn(3,N), column major: 3 per bit
    nm = fortran_data(bp, 'Nm')            # Nm(7,M): 7 per check (0 = unused)
    nrw = fortran_data(bp, 'nrw')
    colorder = fortran_data(par, 'colorder')
    gen = re.findall(r'"([0-9a-f]{22})"', par)
    assert len(mn) == 3 * N and len(nm) == 7 * M and len(nrw) == M and len(colorder) == N and len(gen) == K

    out = []
    out.append('// JS8 (174,87) LDPC code, generated by tools/js8/gen_tables.py from JS8Call\'s')
    out.append('// lib/ft8/bpdecode174.f90 and ldpc_174_87_params.f90. Indices are 0-based.')
    out.append('')
    out.append('// The checks each codeword bit (in transmission order) is in.')
    out.append('static const uint8_t JS8_MN[174][3] = {')
    for n in range(N):
        out.append('    { %s },' % ', '.join(str(v - 1) for v in mn[3 * n:3 * n + 3]))
    out.append('};')
    out.append('')
    out.append('// The bits of each check (unused entries 255) and how many there are.')
    out.append('static const uint8_t JS8_NM[87][7] = {')
    for m in range(M):
        out.append('    { %s },' % ', '.join(str(v - 1) if v else '255' for v in nm[7 * m:7 * m + 7]))
    out.append('};')
    out.append('static const uint8_t JS8_NRW[87] = { %s };' % ', '.join(map(str, nrw)))
    out.append('')
    out.append('// Transmission position of each bit of [87 parity bits, 87 message bits].')
    out.append('static const uint8_t JS8_COLORDER[174] = { %s };' % ', '.join(map(str, colorder)))
    out.append('')
    out.append('// Generator: parity bit i = XOR of the message bits set in row i (MSB first).')
    out.append('static const uint8_t JS8_GEN[87][11] = {')
    for g in gen:
        out.append('    { %s },' % ', '.join('0x' + g[2 * j:2 * j + 2] for j in range(11)))
    out.append('};')
    open(os.path.join(root, 'src/js8_ldpc.inc'), 'w', newline='\n').write('\n'.join(out) + '\n')

    src = open(os.path.join(base, 'jsc_map.cpp'), 'rb').read().decode('latin1')
    src = src[src.index('JSC::map['):]
    src = src[:src.index('};')]
    pat = re.compile(r'\{\s*"((?:[^"\\]|\\.)*)"\s*(?:/\*.*?\*/)?\s*,\s*(\d+)\s*,\s*(\d+)\s*\}')
    words = {}
    for s, n, i in pat.findall(src):
        words[int(i)] = s.encode('latin1').decode('unicode_escape').encode('latin1')
    assert len(words) == 262144, len(words)
    data = bytearray()
    offsets = []
    for i in range(262144):
        if i % JSC_GROUP == 0:
            offsets.append(len(data))
        data += words[i] + b'\0'
    blob = b''.join(struct.pack('<I', o) for o in offsets) + data
    os.makedirs(os.path.join(root, 'data'), exist_ok=True)
    open(os.path.join(root, 'data/jsc_dict.bin'), 'wb').write(blob)
    print('js8_ldpc.inc ok, jsc_dict.bin %d bytes' % len(blob))


if __name__ == '__main__':
    main()
