# Trains the TinyML signal classifier and exports it to include/ml_model.h.
#
#   python tools/ml/train.py [--n 3000] [--extra real.npz ...]
#
# Dataset: synthetic examples from synth.py (n per class) plus, optionally,
# labelled feature vectors recorded from the board (tools/ml/log_to_npz.py).
# Model: MLP N_FEATURES -> 32 -> 16 -> classes, ReLU, softmax; weights
# quantised to int8 (one scale per layer), biases kept in float.
import argparse, os, sys, time
import numpy as np

sys.path.insert(0, os.path.dirname(__file__))
from features import features, CLASSES, N_FEATURES
from synth import example

H1, H2 = 32, 16
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def dataset(n, seed):
    rng = np.random.default_rng(seed)
    X = np.zeros((n * len(CLASSES), N_FEATURES), np.float32)
    y = np.zeros(n * len(CLASSES), np.int64)
    i = 0
    for c, name in enumerate(CLASSES):
        for _ in range(n):
            X[i] = features(example(rng, name))
            y[i] = c
            i += 1
    return X, y


def init(rng):
    def w(a, b):
        return rng.standard_normal((a, b)).astype(np.float32) * np.sqrt(2 / a)
    return [w(N_FEATURES, H1), np.zeros(H1, np.float32),
            w(H1, H2), np.zeros(H2, np.float32),
            w(H2, len(CLASSES)), np.zeros(len(CLASSES), np.float32)]


def forward(p, X):
    h1 = np.maximum(X @ p[0] + p[1], 0)
    h2 = np.maximum(h1 @ p[2] + p[3], 0)
    z = h2 @ p[4] + p[5]
    return h1, h2, z


def softmax(z):
    e = np.exp(z - z.max(axis=1, keepdims=True))
    return e / e.sum(axis=1, keepdims=True)


def train(X, y, epochs=60, lr=3e-3, batch=64, seed=1):
    rng = np.random.default_rng(seed)
    p = init(rng)
    m = [np.zeros_like(a) for a in p]
    v = [np.zeros_like(a) for a in p]
    t = 0
    for ep in range(epochs):
        order = rng.permutation(len(X))
        for s in range(0, len(X), batch):
            idx = order[s:s + batch]
            xb = X[idx] + rng.standard_normal(X[idx].shape).astype(np.float32) * 0.02
            yb = y[idx]
            h1, h2, z = forward(p, xb)
            g = softmax(z)
            g[np.arange(len(yb)), yb] -= 1
            g /= len(yb)
            d2 = (g @ p[4].T) * (h2 > 0)
            d1 = (d2 @ p[2].T) * (h1 > 0)
            grads = [xb.T @ d1, d1.sum(0), h1.T @ d2, d2.sum(0), h2.T @ g, g.sum(0)]
            t += 1
            for k in range(6):
                gk = grads[k] + (1e-4 * p[k] if k % 2 == 0 else 0)
                m[k] = 0.9 * m[k] + 0.1 * gk
                v[k] = 0.999 * v[k] + 0.001 * gk * gk
                p[k] -= lr * (m[k] / (1 - 0.9 ** t)) / (np.sqrt(v[k] / (1 - 0.999 ** t)) + 1e-8)
        if ep == epochs * 2 // 3:
            lr /= 5
    return p


def quantise(p):
    q = []
    for k in range(0, 6, 2):
        s = np.abs(p[k]).max() / 127.0
        q += [np.round(p[k] / s).astype(np.int8), s, p[k + 1]]
    return q


def forward_q(q, X):
    h = X
    for L in range(3):
        w, s, b = q[3 * L:3 * L + 3]
        h = h @ (w.astype(np.float32) * s) + b
        if L < 2:
            h = np.maximum(h, 0)
    return h


def report(name, z, y):
    pred = z.argmax(1)
    print(f"{name}: exatidão {np.mean(pred == y) * 100:.1f}%")
    print("        " + " ".join(f"{c[:5]:>5}" for c in CLASSES))
    for i, c in enumerate(CLASSES):
        row = [np.sum((y == i) & (pred == j)) for j in range(len(CLASSES))]
        print(f"  {c:>5} " + " ".join(f"{r:5d}" for r in row))


def export(q, path):
    with open(path, "w", encoding="utf-8") as f:
        f.write("#pragma once\n// Generated by tools/ml/train.py - do not edit.\n\n#include <stdint.h>\n\n")
        f.write(f"#define ML_N_FEATURES {N_FEATURES}\n#define ML_H1 {H1}\n#define ML_H2 {H2}\n")
        f.write(f"#define ML_N_CLASSES {len(CLASSES)}\n\n")
        f.write("static const char *const ML_CLASS_NAMES[ML_N_CLASSES] = {"
                + ", ".join(f'"{c}"' for c in CLASSES) + "};\n\n")
        names = [("w1", "b1", "ML_N_FEATURES * ML_H1"), ("w2", "b2", "ML_H1 * ML_H2"),
                 ("w3", "b3", "ML_H2 * ML_N_CLASSES")]
        for L, (wn, bn, size) in enumerate(names):
            w, s, b = q[3 * L:3 * L + 3]
            f.write(f"// [in][out], row-major\nstatic const int8_t ML_{wn.upper()}[{size}] = {{\n")
            flat = w.reshape(-1)
            for i in range(0, len(flat), 24):
                f.write("    " + ", ".join(str(int(v)) for v in flat[i:i + 24]) + ",\n")
            f.write("};\n")
            f.write(f"static const float ML_{wn.upper()}_SCALE = {s:.9e}f;\n")
            f.write(f"static const float ML_{bn.upper()}[] = {{"
                    + ", ".join(f"{v:.6e}f" for v in b) + "};\n\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=3000, help="synthetic examples per class")
    ap.add_argument("--extra", nargs="*", default=[], help="npz files with X, y")
    ap.add_argument("--out", default=os.path.join(ROOT, "include", "ml_model.h"))
    a = ap.parse_args()

    t0 = time.time()
    X, y = dataset(a.n, 1)
    Xv, yv = dataset(max(a.n // 5, 50), 2)
    for e in a.extra:
        d = np.load(e)
        X, y = np.concatenate([X, d["X"]]), np.concatenate([y, d["y"]])
    np.savez(os.path.join(os.path.dirname(__file__), "dataset.npz"), X=X, y=y)
    print(f"dataset: {len(X)} treino, {len(Xv)} validação ({time.time() - t0:.0f} s)")

    p = train(X, y)
    report("float treino", forward(p, X)[2], y)
    q = quantise(p)
    report("int8 validação", forward_q(q, Xv), yv)
    export(q, a.out)
    np.savez(os.path.join(os.path.dirname(__file__), "model.npz"), *q)
    print("escrito", a.out)


if __name__ == "__main__":
    main()
