# Renders the world land mask used by the FT8/JS8 station map and writes it to
# include/world_map.h (1 bit per pixel, MSB first, rows top to bottom,
# equirectangular: x = (lon + 180) / 360 * W, y = (90 - lat) / 180 * H).
#   python tools/map/gen_world.py
# Data: Natural Earth 110m land (public domain), downloaded when run.
import json, os, urllib.request
import numpy as np
from PIL import Image, ImageDraw

W, H, SS = 480, 234, 4
URL = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson"
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

geo = json.load(urllib.request.urlopen(URL))
img = Image.new("L", (W * SS, H * SS), 0)
d = ImageDraw.Draw(img)


def pts(ring):
    return [((lon + 180) / 360 * W * SS, (90 - lat) / 180 * H * SS) for lon, lat in ring]


for f in geo["features"]:
    g = f["geometry"]
    polys = g["coordinates"] if g["type"] == "MultiPolygon" else [g["coordinates"]]
    for poly in polys:
        d.polygon(pts(poly[0]), fill=255)
        for hole in poly[1:]:
            d.polygon(pts(hole), fill=0)

small = np.asarray(img.resize((W, H), Image.BOX), np.float32) / 255
bits = small >= 0.3
packed = np.packbits(bits, axis=1)
out = os.path.join(ROOT, "include", "world_map.h")
with open(out, "w", encoding="utf-8") as fh:
    fh.write("#pragma once\n// Generated by tools/map/gen_world.py - do not edit.\n\n#include <stdint.h>\n\n")
    fh.write(f"#define WORLD_MAP_W {W}\n#define WORLD_MAP_H {H}\n#define WORLD_MAP_ROW_BYTES {packed.shape[1]}\n\n")
    fh.write("// Land = 1, MSB first, equirectangular, row 0 at 90 N.\n")
    fh.write("inline constexpr uint8_t WORLD_MAP[WORLD_MAP_H * WORLD_MAP_ROW_BYTES] = {\n")
    flat = packed.reshape(-1)
    for i in range(0, len(flat), 24):
        fh.write("    " + ", ".join(f"0x{v:02x}" for v in flat[i:i + 24]) + ",\n")
    fh.write("};\n")
print("land", bits.mean() * 100, "% ->", out)
# Preview
Image.fromarray((bits * 255).astype(np.uint8)).save(os.path.join(os.path.dirname(__file__), "preview.png"))
