#include "lcd_ui.h"

#include "config.h"

#if LCD_UI

#include <stdio.h>
#include <string.h>
#include <time.h>
#include <initializer_list>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/gpio.h"
#include "driver/i2c_master.h"
#include "driver/ledc.h"
#include "driver/spi_master.h"
#include "esp_heap_caps.h"
#include "esp_lcd_panel_io.h"
#include "esp_lcd_panel_ops.h"
#include "esp_lcd_st7796.h"
#include "esp_log.h"
#include "esp_system.h"
#include "esp_timer.h"
#include "esp_lvgl_port.h"
#include "lvgl.h"

#include "analyzer.h"
#include "fax_decoder.h"
#include "ftx_decoder.h"
#include "settings.h"
#include "sstv_decoder.h"
#include "ui_hub.h"
#include "web_ui.h"

static const char *TAG = "LCD";

// Touch coordinates come in the panel's native portrait frame (320 x 480);
// these map them onto the landscape screen.
#define TOUCH_ADDR      0x38    // FT6336U
#define TOUCH_SWAP_XY   1
#define TOUCH_MIRROR_X  0
#define TOUCH_MIRROR_Y  1
#define TOUCH_DEBUG     0       // 1 = log every touch (raw and mapped)

// Backlight PWM at 24 kHz: its alias at the 48 kHz ADC rate falls on a zero
// of the x4 decimation boxcar instead of in the audio band.
#define BL_PWM_HZ       24000

// Layout (landscape 480 x 320)
#define STATUS_H        22
#define TABBAR_H        36
#define CONTENT_H       (LCD_V_RES - STATUS_H - TABBAR_H)    // 262
#define SPEC_H          56
#define WF_H            138
#define TEXT_TAG_W      30      // "CW" / "RT" in front of the text lines
#define TEXT_KEEP       300     // characters kept for the two-line view
#define TEXT_TAB_LINES  25      // lines kept in the Text tab (as shown, after wrapping)
#define IMG_BAR_H       36      // Image tab: state + buttons under the picture
#define IMG_BTN_H       30
#define IMG_H           (CONTENT_H - IMG_BAR_H)
#define FTX_ROWS        50      // FT8/FT4 messages kept, newest first
#define FTX_BAR_H       28      // FT8 tab: mode + state line above the table
#define FTX_MODE_W      92

// Montserrat Medium with Latin-1 (accented letters) and LVGL's symbols,
// generated by tools/gen_fonts.sh (components/ui_fonts): the built-in fonts
// only have ASCII.
LV_FONT_DECLARE(font_ui_12)
LV_FONT_DECLARE(font_ui_14)
LV_FONT_DECLARE(font_ui_16)

// ---------------------------------------------------------------------------
// Texts, Portuguese (pt-PT) and English (g_settings.language). UTF-8.

#define UI_STRINGS(X) \
    X(S_TAB_TEXT,       "Texto", "Text") \
    X(S_TAB_IMAGE,      "Imagem", "Image") \
    X(S_FTX_MODES,      "Desligado\nFT8\nFT4", "Off\nFT8\nFT4") \
    X(S_FTX_OFF,        "Desligado", "Off") \
    X(S_FTX_NO_TIME,    "sem hora UTC (Wi-Fi/NTP)", "no UTC time (Wi-Fi/NTP)") \
    X(S_FTX_LAST,       "último período: %d msg, %d ms", "last slot: %d msg, %d ms") \
    X(S_FTX_WAIT,       "à espera do primeiro período", "waiting for the first slot") \
    X(S_FTX_MESSAGE,    "Mensagem", "Message") \
    X(S_IMG_NONE,       "Sem imagem", "No image") \
    X(S_IMG_LINES,      "linhas", "lines") \
    X(S_IMG_RECEIVING,  "(a receber)", "(receiving)") \
    X(S_IMG_STOP,       "Parar", "Stop")     X(S_CLEAR,          "Limpar", "Clear") \
    X(S_CFG_CW_AUTO,    "CW: tom automático", "CW: automatic tone") \
    X(S_CFG_CONTRAST,   "CW: contraste mínimo", "CW: minimum contrast") \
    X(S_CFG_RTTY_BAUD,  "RTTY: velocidade", "RTTY: speed") \
    X(S_CFG_RTTY_POL,   "RTTY: polaridade", "RTTY: polarity") \
    X(S_RTTY_POLS,      "Automática\nNormal\nInvertida", "Automatic\nNormal\nReversed") \
    X(S_CFG_FAX_LPM,    "FAX: linhas/min", "FAX: lines/min") \
    X(S_CFG_FAX_AUTO,   "FAX: início automático", "FAX: automatic start") \
    X(S_CFG_SSTV_ADJ,   "SSTV: ajuste automático", "SSTV: automatic adjust") \
    X(S_CFG_BRIGHT,     "Brilho", "Brightness") \
    X(S_CFG_WEB,        "Wi-Fi e página web", "Wi-Fi and web page") \
    X(S_CFG_WEB_NOTE,   "reinicia para aplicar", "restart to apply") \
    X(S_CFG_RESTART,    "Reiniciar a placa", "Restart the board") \
    X(S_RESTART,        "Reiniciar", "Restart") \
    X(S_WIFI_OFF,       "desligado", "off") \
    X(S_WIFI_JOINING,   "a ligar...", "connecting...") \
    X(S_WIFI_AP,        "  + ponto de acesso RX-Analyzer (192.168.4.1)", \
                        "  + access point RX-Analyzer (192.168.4.1)") \
    X(S_WIFI_NETWORKS,  "Redes Wi-Fi", "Wi-Fi networks") \
    X(S_WIFI_SCANNING,  "A procurar redes...", "Scanning for networks...") \
    X(S_WIFI_NONE_FOUND, "Nenhuma rede encontrada", "No networks found") \
    X(S_WIFI_PASSWORD,  "Palavra-passe", "Password") \
    X(S_WIFI_SHOW,      "Mostrar", "Show") \
    X(S_WIFI_CONNECT,   "Ligar", "Connect") \
    X(S_CANCEL,         "Cancelar", "Cancel") \
    X(S_CLOSE,          "Fechar", "Close") \
    X(S_WIFI_CONNECTING, "A ligar a %s...", "Connecting to %s...") \
    X(S_WIFI_CONNECTED, "Ligado a %s\nEndereço: %s", "Connected to %s\nAddress: %s") \
    X(S_WIFI_BAD_PASS,  "Palavra-passe incorreta", "Wrong password") \
    X(S_WIFI_NO_AP,     "Rede não encontrada", "Network not found") \
    X(S_WIFI_FAILED,    "Não foi possível ligar", "Could not connect") \
    X(S_NET_NONE,       "(nenhuma)", "(none)") \
    X(S_INFO_NET,       "Rede", "Network") \
    X(S_INFO_BOOT,      "Arranque", "Boot") \
    X(S_INFO_RESETS,    "reinícios inesperados", "unexpected resets") \
    X(S_INFO_LOAD,      "Carga da análise", "Analysis load") \
    X(S_INFO_RAM,       "RAM livre", "Free RAM")

#define UI_STR_ID(id, pt, en) id,
enum Str { UI_STRINGS(UI_STR_ID) S_COUNT };
#define UI_STR_TEXT(id, pt, en) { pt, en },
static const char *const STRINGS[S_COUNT][2] = { UI_STRINGS(UI_STR_TEXT) };

static const char *tr(Str id)
{
    return STRINGS[id][g_settings.language == LANG_EN ? 1 : 0];
}

// Why the board (re)started, as in main.cpp but in both languages.
static const char *boot_reason_text()
{
    const bool en = g_settings.language == LANG_EN;
    switch (esp_reset_reason()) {
    case ESP_RST_POWERON:   return en ? "power on" : "ligação da alimentação";
    case ESP_RST_EXT:       return en ? "reset button" : "botão de reset";
    case ESP_RST_SW:        return en ? "software restart" : "reinício pedido";
    case ESP_RST_USB:       return en ? "USB (programming)" : "USB (programação)";
    case ESP_RST_JTAG:      return "JTAG";
    case ESP_RST_DEEPSLEEP: return "deep sleep";
    case ESP_RST_PANIC:     return en ? "software error (panic)" : "erro de software (panic)";
    case ESP_RST_INT_WDT:   return en ? "interrupt watchdog" : "watchdog de interrupções";
    case ESP_RST_TASK_WDT:  return en ? "task watchdog" : "watchdog de tarefas";
    case ESP_RST_WDT:       return "watchdog";
    case ESP_RST_BROWNOUT:  return en ? "brownout" : "quebra de tensão (brownout)";
    case ESP_RST_PWR_GLITCH: return en ? "power glitch" : "falha na alimentação";
    case ESP_RST_CPU_LOCKUP: return en ? "CPU lockup" : "CPU bloqueado";
    default:                return en ? "unknown reason" : "motivo desconhecido";
    }
}

// The analyzer's signal label (status bar) is built in Portuguese without
// accents; its words are swapped here.
static void translate_label(const char *in, char *out, size_t size)
{
    static const char *const WORDS[][3] = {    // analyzer, pt-PT, en
        { "RUIDO", "RUÍDO", "NOISE" }, { "TOM", "TOM", "TONE" }, { "LARGO", "LARGO", "WIDE" },
        { "(voz?)", "(voz?)", "(voice?)" }, { "fase", "fase", "phasing" }, { "VOZ", "VOZ", "VOICE" },
    };
    const int lang = g_settings.language == LANG_EN ? 2 : 1;
    size_t o = 0;
    out[0] = 0;
    while (*in && o + 1 < size) {
        const size_t len = strcspn(in, " ");
        const char *word = nullptr;
        for (const auto &w : WORDS)
            if (strlen(w[0]) == len && !strncmp(in, w[0], len))
                word = w[lang];
        o += snprintf(out + o, size - o, "%.*s", word ? (int)strlen(word) : (int)len, word ? word : in);
        if (o >= size)
            break;
        in += len;
        while (*in == ' ' && o + 1 < size) {
            out[o++] = ' ';
            in++;
        }
        out[o] = 0;
    }
}

// ---------------------------------------------------------------------------
// LVGL heap (CONFIG_LV_USE_CUSTOM_MALLOC): widgets, styles and text in PSRAM.

extern "C" {
void lv_mem_init(void) {}
void lv_mem_deinit(void) {}
lv_mem_pool_t lv_mem_add_pool(void *, size_t) { return nullptr; }
void lv_mem_remove_pool(lv_mem_pool_t) {}
void *lv_malloc_core(size_t size) { return heap_caps_malloc(size, MALLOC_CAP_SPIRAM); }
void *lv_realloc_core(void *p, size_t size) { return heap_caps_realloc(p, size, MALLOC_CAP_SPIRAM); }
void lv_free_core(void *p) { heap_caps_free(p); }
void lv_mem_monitor_core(lv_mem_monitor_t *) {}
lv_result_t lv_mem_test_core(void) { return LV_RESULT_OK; }
}

// ---------------------------------------------------------------------------
// Hardware: backlight, panel, touch

static i2c_master_bus_handle_t i2c_bus;
static i2c_master_dev_handle_t touch_dev;

static void backlight_init()
{
    ledc_timer_config_t t = {};
    t.speed_mode = LEDC_LOW_SPEED_MODE;
    t.duty_resolution = LEDC_TIMER_10_BIT;
    t.timer_num = LEDC_TIMER_0;
    t.freq_hz = BL_PWM_HZ;
    t.clk_cfg = LEDC_AUTO_CLK;
    ESP_ERROR_CHECK(ledc_timer_config(&t));
    ledc_channel_config_t c = {};
    c.gpio_num = LCD_PIN_BL;
    c.speed_mode = LEDC_LOW_SPEED_MODE;
    c.channel = LEDC_CHANNEL_0;
    c.timer_sel = LEDC_TIMER_0;
    c.duty = 0;
    ESP_ERROR_CHECK(ledc_channel_config(&c));
}

static void backlight_set(int percent)
{
    const uint32_t duty = percent >= 100 ? 1024 : (uint32_t)percent * 1023 / 100;
    ledc_set_duty(LEDC_LOW_SPEED_MODE, LEDC_CHANNEL_0, duty);
    ledc_update_duty(LEDC_LOW_SPEED_MODE, LEDC_CHANNEL_0);
}

static void panel_init(esp_lcd_panel_io_handle_t *io, esp_lcd_panel_handle_t *panel)
{
    spi_bus_config_t bus = {};
    bus.sclk_io_num = (gpio_num_t)LCD_PIN_SCK;
    bus.mosi_io_num = (gpio_num_t)LCD_PIN_MOSI;
    bus.miso_io_num = (gpio_num_t)LCD_PIN_MISO;
    bus.quadwp_io_num = GPIO_NUM_NC;
    bus.quadhd_io_num = GPIO_NUM_NC;
    bus.max_transfer_sz = LCD_H_RES * 20 * sizeof(uint16_t);
    ESP_ERROR_CHECK(spi_bus_initialize(LCD_SPI_HOST, &bus, SPI_DMA_CH_AUTO));

    esp_lcd_panel_io_spi_config_t io_cfg = {};
    io_cfg.cs_gpio_num = (gpio_num_t)LCD_PIN_CS;
    io_cfg.dc_gpio_num = (gpio_num_t)LCD_PIN_DC;
    io_cfg.spi_mode = 0;
    io_cfg.pclk_hz = LCD_SPI_HZ;
    io_cfg.trans_queue_depth = 10;
    io_cfg.lcd_cmd_bits = 8;
    io_cfg.lcd_param_bits = 8;
    ESP_ERROR_CHECK(esp_lcd_new_panel_io_spi((esp_lcd_spi_bus_handle_t)LCD_SPI_HOST, &io_cfg, io));

    // RESET is tied to the chip's EN: software reset only.
    esp_lcd_panel_dev_config_t cfg = {};
    cfg.reset_gpio_num = GPIO_NUM_NC;
    cfg.rgb_ele_order = LCD_RGB_ELEMENT_ORDER_BGR;
    cfg.bits_per_pixel = 16;
    ESP_ERROR_CHECK(esp_lcd_new_panel_st7796(*io, &cfg, panel));
    ESP_ERROR_CHECK(esp_lcd_panel_reset(*panel));
    ESP_ERROR_CHECK(esp_lcd_panel_init(*panel));
    ESP_ERROR_CHECK(esp_lcd_panel_invert_color(*panel, true));
    ESP_ERROR_CHECK(esp_lcd_panel_disp_on_off(*panel, true));
}

static void touch_init()
{
    i2c_master_bus_config_t bus = {};
    bus.i2c_port = I2C_NUM_0;
    bus.sda_io_num = (gpio_num_t)BOARD_I2C_SDA;
    bus.scl_io_num = (gpio_num_t)BOARD_I2C_SCL;
    bus.clk_source = I2C_CLK_SRC_DEFAULT;
    bus.glitch_ignore_cnt = 7;
    bus.flags.enable_internal_pullup = true;    // external 10 k are fitted too
    ESP_ERROR_CHECK(i2c_new_master_bus(&bus, &i2c_bus));

    gpio_config_t io = {};
    io.pin_bit_mask = 1ULL << TOUCH_PIN_RST;
    io.mode = GPIO_MODE_OUTPUT;
    gpio_config(&io);
    gpio_set_level((gpio_num_t)TOUCH_PIN_RST, 0);
    vTaskDelay(pdMS_TO_TICKS(10));
    gpio_set_level((gpio_num_t)TOUCH_PIN_RST, 1);
    vTaskDelay(pdMS_TO_TICKS(300));

    i2c_device_config_t dev = {};
    dev.dev_addr_length = I2C_ADDR_BIT_LEN_7;
    dev.device_address = TOUCH_ADDR;
    dev.scl_speed_hz = 400000;
    ESP_ERROR_CHECK(i2c_master_bus_add_device(i2c_bus, &dev, &touch_dev));
    if (i2c_master_probe(i2c_bus, TOUCH_ADDR, 50) != ESP_OK)
        ESP_LOGW(TAG, "touch (FT6336U, 0x%02x) nao responde", TOUCH_ADDR);
}

// LVGL input device: polls the FT6336U (TD_STATUS and the first point).
static void touch_read_cb(lv_indev_t *, lv_indev_data_t *data)
{
    static int16_t last_x = 0, last_y = 0;
    uint8_t reg = 0x02, b[5];
    data->state = LV_INDEV_STATE_RELEASED;
    if (i2c_master_transmit_receive(touch_dev, &reg, 1, b, sizeof(b), 20) == ESP_OK && (b[0] & 0x0F) > 0) {
        int x = ((b[1] & 0x0F) << 8) | b[2];
        int y = ((b[3] & 0x0F) << 8) | b[4];
        const int rx = x, ry = y;
#if TOUCH_SWAP_XY
        const int t = x; x = y; y = t;
#endif
#if TOUCH_MIRROR_X
        x = LCD_H_RES - 1 - x;
#endif
#if TOUCH_MIRROR_Y
        y = LCD_V_RES - 1 - y;
#endif
        last_x = x < 0 ? 0 : x >= LCD_H_RES ? LCD_H_RES - 1 : x;
        last_y = y < 0 ? 0 : y >= LCD_V_RES ? LCD_V_RES - 1 : y;
        data->state = LV_INDEV_STATE_PRESSED;
        if (TOUCH_DEBUG)
            ESP_LOGW(TAG, "touch raw %d,%d -> %d,%d", rx, ry, last_x, last_y);
    }
    data->point.x = last_x;
    data->point.y = last_y;
}

// ---------------------------------------------------------------------------
// Widgets

static lv_obj_t *tabview;
static lv_obj_t *tab_rx, *tab_text, *tab_ftx, *tab_img, *tab_cfg;
static lv_obj_t *lbl_mode, *lbl_info;
static lv_obj_t *spec_canvas, *wf_canvas, *img_canvas;
static uint16_t *spec_buf, *wf_buf, *img_buf;
static lv_obj_t *lbl_cw_line, *lbl_rtty_line;
static lv_obj_t *ta_cw, *ta_rtty;
static lv_obj_t *ftx_table, *lbl_ftx_state;
static lv_obj_t *lbl_img_info;
static lv_obj_t *lbl_cfg_info, *lbl_contrast, *lbl_bright, *lbl_web_note;

static uint16_t wf_lut[256];
static UiStatus last_status;

static inline uint16_t rgb565(int r, int g, int b)
{
    return (uint16_t)(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3));
}

// Waterfall palette, as on the web page: black, blue, cyan, yellow, red, white.
static void build_lut()
{
    static const uint8_t stops[][3] = {
        {0, 0, 0}, {0, 0, 200}, {0, 200, 220}, {240, 240, 0}, {240, 0, 0}, {255, 255, 255},
    };
    const int n = sizeof(stops) / sizeof(stops[0]) - 1;
    for (int i = 0; i < 256; i++) {
        const float p = i / 255.0f * n;
        const int k = p >= n ? n - 1 : (int)p;
        const float f = p - k;
        wf_lut[i] = rgb565(stops[k][0] + (stops[k + 1][0] - stops[k][0]) * f,
                           stops[k][1] + (stops[k + 1][1] - stops[k][1]) * f,
                           stops[k][2] + (stops[k + 1][2] - stops[k][2]) * f);
    }
}

static float col_hz(int col)
{
    return (col + 0.5f) * UI_BINS / LCD_H_RES * DSP_SAMPLE_RATE / FFT_SIZE;
}

static int hz_col(float hz)
{
    return (int)(hz * FFT_SIZE / DSP_SAMPLE_RATE * LCD_H_RES / UI_BINS);
}

static lv_obj_t *make_canvas(lv_obj_t *parent, uint16_t **buf, int w, int h)
{
    if (!*buf)    // kept across rebuilds (language change)
        *buf = (uint16_t *)heap_caps_calloc(w * h, sizeof(uint16_t), MALLOC_CAP_SPIRAM);
    lv_obj_t *c = lv_canvas_create(parent);
    lv_canvas_set_buffer(c, *buf, w, h, LV_COLOR_FORMAT_RGB565);
    return c;
}

// ---------------------------------------------------------------------------
// Spectrum + waterfall

// Level byte: 0.5 dB steps from -120 dBFS. The colour scale follows the noise
// floor (20th percentile of each row, smoothed) and spans WF_SPAN.
#define WF_SPAN  100    // 50 dB
static float wf_floor = -1.0f;

static void draw_rows(const uint8_t (*rows)[UI_BINS], int n)
{
    for (int r = 0; r < n; r++) {
        const uint8_t *row = rows[r];
        uint16_t hist[256] = {};
        for (int i = 0; i < UI_BINS; i++)
            hist[row[i]]++;
        int q = 0;
        for (int acc = 0; q < 255 && (acc += hist[q]) < UI_BINS / 5; q++) {}
        wf_floor = wf_floor < 0.0f ? q : wf_floor + (q - wf_floor) * 0.05f;
        const int lo = (int)wf_floor - 6;

        memmove(wf_buf + LCD_H_RES, wf_buf, LCD_H_RES * (WF_H - 1) * sizeof(uint16_t));
        for (int c = 0; c < LCD_H_RES; c++) {
            int v = (row[c * UI_BINS / LCD_H_RES] - lo) * 255 / WF_SPAN;
            wf_buf[c] = wf_lut[v < 0 ? 0 : v > 255 ? 255 : v];
        }
    }
    if (!n)
        return;

    // Spectrum of the newest row, with a 500 Hz grid and the decoder tones.
    const uint8_t *row = rows[n - 1];
    const int lo = (int)wf_floor - 6;
    const uint16_t bg = rgb565(8, 12, 24), grid = rgb565(40, 48, 70), bar = rgb565(80, 200, 120);
    for (int i = 0; i < LCD_H_RES * SPEC_H; i++)
        spec_buf[i] = bg;
    for (int hz = 500; col_hz(LCD_H_RES - 1) > hz; hz += 500) {
        const int c = hz_col(hz);
        for (int y = 0; y < SPEC_H; y++)
            spec_buf[y * LCD_H_RES + c] = grid;
    }
    for (int c = 0; c < LCD_H_RES; c++) {
        int h = (row[c * UI_BINS / LCD_H_RES] - lo) * SPEC_H / WF_SPAN;
        h = h < 0 ? 0 : h > SPEC_H ? SPEC_H : h;
        for (int y = SPEC_H - h; y < SPEC_H; y++)
            spec_buf[y * LCD_H_RES + c] = bar;
    }
    auto marker = [](float hz, uint16_t color) {
        const int c = hz_col(hz);
        if (hz > 0.0f && c >= 0 && c < LCD_H_RES)
            for (int y = 0; y < SPEC_H; y += 2)
                spec_buf[y * LCD_H_RES + c] = color;
    };
    marker(last_status.tone_hz, rgb565(255, 60, 60));
    if (last_status.rtty_active) {
        marker(last_status.rtty_mark_hz, rgb565(255, 220, 0));
        marker(last_status.rtty_space_hz, rgb565(255, 220, 0));
    }
    if (!g_settings.cw_auto_tone)
        marker(g_settings.cw_tone_hz, rgb565(255, 255, 255));

    lv_obj_invalidate(spec_canvas);
    lv_obj_invalidate(wf_canvas);
}

// Tap on the spectrum/waterfall: manual CW tone there; long press: automatic.
static void spectrum_event(lv_event_t *e)
{
    lv_obj_t *obj = (lv_obj_t *)lv_event_get_target(e);
    if (lv_event_get_code(e) == LV_EVENT_LONG_PRESSED) {
        g_settings.cw_auto_tone = true;
    } else {
        lv_point_t p;
        lv_indev_get_point(lv_indev_active(), &p);
        lv_area_t a;
        lv_obj_get_coords(obj, &a);
        const float hz = col_hz(p.x - a.x1);
        if (hz < SPECTRUM_MIN_HZ || hz > SPECTRUM_MAX_HZ)
            return;
        g_settings.cw_auto_tone = false;
        g_settings.cw_tone_hz = hz;
    }
    settings_save();
}

// ---------------------------------------------------------------------------
// Text

struct TextView {
    UiTextChannel ch;
    uint32_t seq;
    char tail[TEXT_KEEP + 1];    // newest characters, line breaks flattened
    int len;
};
static TextView text_views[2] = { { UI_TEXT_CW, 0, "", 0 }, { UI_TEXT_RTTY, 0, "", 0 } };

// Drops the oldest lines of a text area beyond TEXT_TAB_LINES, counting the
// lines as displayed (wrapped). The text is ASCII, so letters = bytes.
static void trim_lines(lv_obj_t *ta)
{
    lv_obj_t *lbl = lv_textarea_get_label(ta);
    lv_obj_update_layout(ta);
    const int32_t line_h = lv_font_get_line_height(lv_obj_get_style_text_font(lbl, LV_PART_MAIN)) +
                           lv_obj_get_style_text_line_space(lbl, LV_PART_MAIN);
    const int lines = line_h > 0 ? lv_obj_get_height(lbl) / line_h : 0;
    if (lines <= TEXT_TAB_LINES)
        return;
    lv_point_t p = { 0, (lines - TEXT_TAB_LINES) * line_h + line_h / 2 };
    const uint32_t first = lv_label_get_letter_on(lbl, &p, false);
    static char keep[UI_TEXT_RING + 1];
    strlcpy(keep, lv_textarea_get_text(ta) + first, sizeof(keep));
    lv_textarea_set_text(ta, keep);
}

static void update_text(TextView &tv, lv_obj_t *line_lbl, lv_obj_t *ta)
{
    static char buf[UI_TEXT_RING + 1];
    const int n = ui_get_text(tv.ch, tv.seq, buf, &tv.seq);
    if (n <= 0)
        return;

    lv_textarea_set_cursor_pos(ta, LV_TEXTAREA_CURSOR_LAST);    // always append at the end
    lv_textarea_add_text(ta, buf);
    trim_lines(ta);

    // RX tab: the label wraps and sits at the bottom of a two-line box, so
    // the newest text shows and older lines move up out of view.
    for (int i = 0; i < n; i++) {
        if (tv.len == TEXT_KEEP) {
            memmove(tv.tail, tv.tail + TEXT_KEEP / 3, tv.len - TEXT_KEEP / 3);
            tv.len -= TEXT_KEEP / 3;
        }
        const char c = buf[i];
        tv.tail[tv.len++] = c == '\n' || c == '\r' ? ' ' : c;
    }
    tv.tail[tv.len] = 0;
    lv_label_set_text(line_lbl, tv.tail);
}

// ---------------------------------------------------------------------------
// FT8 / FT4

static FtxMessage ftx_list[FTX_ROWS];    // newest first
static int ftx_count = 0;
static uint32_t ftx_seq = 0;

static void update_ftx()
{
    static FtxMessage fresh[UI_FTX_RING];
    const int n = ui_get_ftx(ftx_seq, fresh, &ftx_seq);
    if (n > 0) {
        const int add = n < FTX_ROWS ? n : FTX_ROWS;
        const int keep = ftx_count + add > FTX_ROWS ? FTX_ROWS - add : ftx_count;
        memmove(ftx_list + add, ftx_list, keep * sizeof(FtxMessage));
        for (int i = 0; i < add; i++)
            ftx_list[i] = fresh[n - 1 - i];
        ftx_count = keep + add;
        lv_table_set_row_count(ftx_table, ftx_count + 1);
        for (int i = 0; i < ftx_count; i++) {
            const FtxMessage &m = ftx_list[i];
            const time_t t = (time_t)m.slot_start;
            struct tm tm;
            gmtime_r(&t, &tm);
            char s[16];
            snprintf(s, sizeof(s), "%02d%02d%02d", tm.tm_hour, tm.tm_min, tm.tm_sec);
            lv_table_set_cell_value(ftx_table, i + 1, 0, s);
            snprintf(s, sizeof(s), "%.0f", m.snr_db);
            lv_table_set_cell_value(ftx_table, i + 1, 1, s);
            snprintf(s, sizeof(s), "%.1f", m.dt);
            lv_table_set_cell_value(ftx_table, i + 1, 2, s);
            snprintf(s, sizeof(s), "%.0f", m.freq_hz);
            lv_table_set_cell_value(ftx_table, i + 1, 3, s);
            lv_table_set_cell_value(ftx_table, i + 1, 4, m.text);
        }
    }
    char s[128];
    const int last = ftx_last_count();
    if (g_settings.ftx_mode == FTX_OFF)
        snprintf(s, sizeof(s), "%s", tr(S_FTX_OFF));
    else if (!ftx_time_ok())
        snprintf(s, sizeof(s), LV_SYMBOL_WARNING " %s", tr(S_FTX_NO_TIME));
    else if (last >= 0)
        snprintf(s, sizeof(s), tr(S_FTX_LAST), last, ftx_last_ms());
    else
        snprintf(s, sizeof(s), "%s", tr(S_FTX_WAIT));
    lv_label_set_text(lbl_ftx_state, s);
}

// ---------------------------------------------------------------------------
// Image (FAX / SSTV)

// FAX (grey) by default: full width, newest lines at the bottom (a long
// chart scrolls up). SSTV (colour, short) by default: the whole image. A tap
// swaps the two views.
static bool img_swap = false;
static uint32_t img_drawn_id = 0, img_drawn_lines = 0;
static int64_t img_drawn_us = 0;

static void render_image(bool force)
{
    const UiImageInfo info = ui_get_image_info();
    char s[96];
    if (!info.id || !info.width) {
        lv_label_set_text(lbl_img_info, tr(S_IMG_NONE));
        return;
    }
    snprintf(s, sizeof(s), "%s  %u %s  %s", info.title, (unsigned)info.lines, tr(S_IMG_LINES),
             info.active ? tr(S_IMG_RECEIVING) : "");
    lv_label_set_text(lbl_img_info, s);

    const int64_t now = esp_timer_get_time();
    if (!force && info.id == img_drawn_id &&
        (info.lines == img_drawn_lines || now - img_drawn_us < 500000))
        return;

    const uint32_t held = info.lines - info.first;
    const float aspect = info.aspect > 0.0f ? info.aspect : 1.0f;
    for (int i = 0; i < LCD_H_RES * IMG_H; i++)
        img_buf[i] = 0;
    if (held > 0) {
        float scale;
        uint32_t first = info.first;
        const bool scroll = (info.channels == 1) != img_swap;
        if (scroll) {
            scale = (float)LCD_H_RES / info.width;
            const uint32_t fit = (uint32_t)(IMG_H / (aspect * scale));
            if (held > fit)
                first = info.lines - fit;
        } else {
            const float sw = (float)LCD_H_RES / info.width, sh = IMG_H / (held * aspect);
            scale = sw < sh ? sw : sh;
        }
        const int out_w = (int)(info.width * scale);
        const int out_h = (int)((info.lines - first) * aspect * scale);
        const int x0 = (LCD_H_RES - out_w) / 2;
        static uint8_t line[UI_IMG_MAX_LINE];
        uint32_t loaded = UINT32_MAX;
        for (int y = 0; y < out_h && y < IMG_H; y++) {
            const uint32_t k = first + (uint32_t)(y / (aspect * scale));
            if (k >= info.lines)
                break;
            if (k != loaded) {
                if (!ui_get_image_lines(info.id, k, 1, line))
                    return;    // changed meanwhile: next time
                loaded = k;
            }
            uint16_t *dst = img_buf + y * LCD_H_RES + x0;
            for (int x = 0; x < out_w; x++) {
                const int sx = (int)(x / scale);
                if (info.channels == 3) {
                    const uint8_t *p = line + sx * 3;
                    dst[x] = rgb565(p[0], p[1], p[2]);
                } else {
                    const uint8_t g = line[sx];
                    dst[x] = rgb565(g, g, g);
                }
            }
        }
    }
    img_drawn_id = info.id;
    img_drawn_lines = info.lines;
    img_drawn_us = now;
    lv_obj_invalidate(img_canvas);
}

static void image_event(lv_event_t *)
{
    img_swap = !img_swap;
    render_image(true);
}

static void fax_start_event(lv_event_t *) { fax_request_start(); }

static void img_stop_event(lv_event_t *)
{
    fax_request_stop();
    sstv_request_stop();
}

// ---------------------------------------------------------------------------
// Settings

enum CfgId {
    CFG_CW_AUTO, CFG_CONTRAST, CFG_RTTY_BAUD, CFG_RTTY_POL, CFG_FAX_LPM, CFG_FAX_IOC,
    CFG_FAX_AUTO, CFG_SSTV_ADJ, CFG_FTX_MODE, CFG_BRIGHT, CFG_WEB, CFG_LANGUAGE,
};

static void rebuild_ui(void *);

static const float RTTY_BAUDS[] = { 45.45f, 50.0f, 75.0f, 100.0f };
static const int FAX_LPMS[] = { 60, 90, 120, 240 };
static const int FAX_IOCS[] = { 576, 288 };

static lv_obj_t *sw_cw_auto;

static void cfg_event(lv_event_t *e)
{
    const CfgId id = (CfgId)(intptr_t)lv_event_get_user_data(e);
    lv_obj_t *obj = (lv_obj_t *)lv_event_get_target(e);
    const lv_event_code_t code = lv_event_get_code(e);
    const bool checked = lv_obj_has_state(obj, LV_STATE_CHECKED);
    bool save = true;
    switch (id) {
    case CFG_CW_AUTO:   g_settings.cw_auto_tone = checked; break;
    case CFG_CONTRAST:
        g_settings.cw_min_contrast = lv_slider_get_value(obj) / 10.0f;
        lv_label_set_text_fmt(lbl_contrast, "%.1f", g_settings.cw_min_contrast);
        save = code == LV_EVENT_RELEASED;
        break;
    case CFG_RTTY_BAUD: g_settings.rtty_baud = RTTY_BAUDS[lv_dropdown_get_selected(obj)]; break;
    case CFG_RTTY_POL:  g_settings.rtty_polarity = lv_dropdown_get_selected(obj); break;
    case CFG_FAX_LPM:   g_settings.fax_lpm = FAX_LPMS[lv_dropdown_get_selected(obj)]; break;
    case CFG_FAX_IOC:   g_settings.fax_ioc = FAX_IOCS[lv_dropdown_get_selected(obj)]; break;
    case CFG_FAX_AUTO:  g_settings.fax_auto = checked; break;
    case CFG_SSTV_ADJ:  g_settings.sstv_adjust = checked; break;
    case CFG_FTX_MODE:  g_settings.ftx_mode = lv_dropdown_get_selected(obj); break;
    case CFG_BRIGHT:
        g_settings.lcd_brightness = lv_slider_get_value(obj);
        lv_label_set_text_fmt(lbl_bright, "%d %%", g_settings.lcd_brightness);
        backlight_set(g_settings.lcd_brightness);
        save = code == LV_EVENT_RELEASED;
        break;
    case CFG_WEB:
        g_settings.web_enabled = checked;
        lv_label_set_text(lbl_web_note, tr(S_CFG_WEB_NOTE));
        break;
    case CFG_LANGUAGE:
        g_settings.language = lv_dropdown_get_selected(obj) ? LANG_EN : LANG_PT;
        lv_async_call(rebuild_ui, nullptr);    // not from inside this widget's own event
        break;
    }
    settings_apply();
    if (save)
        settings_save();
}

static void restart_event(lv_event_t *)
{
    esp_restart();
}

static lv_obj_t *cfg_row(lv_obj_t *parent, const char *text)
{
    lv_obj_t *row = lv_obj_create(parent);
    lv_obj_set_size(row, lv_pct(100), LV_SIZE_CONTENT);
    lv_obj_set_style_pad_all(row, 4, 0);
    lv_obj_set_style_border_width(row, 0, 0);
    lv_obj_set_style_bg_opa(row, LV_OPA_TRANSP, 0);
    lv_obj_set_flex_flow(row, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(row, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollable(row, false);
    lv_obj_t *l = lv_label_create(row);
    lv_label_set_text(l, text);
    lv_obj_set_flex_grow(l, 1);
    return row;
}

static lv_obj_t *cfg_switch(lv_obj_t *parent, const char *text, bool on, CfgId id)
{
    lv_obj_t *sw = lv_switch_create(cfg_row(parent, text));
    if (on)
        lv_obj_add_state(sw, LV_STATE_CHECKED);
    lv_obj_add_event_cb(sw, cfg_event, LV_EVENT_VALUE_CHANGED, (void *)(intptr_t)id);
    return sw;
}

static lv_obj_t *cfg_dropdown(lv_obj_t *parent, const char *text, const char *opts, int sel, CfgId id)
{
    lv_obj_t *dd = lv_dropdown_create(cfg_row(parent, text));
    lv_dropdown_set_options(dd, opts);
    lv_dropdown_set_selected(dd, sel < 0 ? 0 : sel);
    lv_obj_set_width(dd, 150);
    lv_obj_add_event_cb(dd, cfg_event, LV_EVENT_VALUE_CHANGED, (void *)(intptr_t)id);
    return dd;
}

static lv_obj_t *cfg_slider(lv_obj_t *parent, const char *text, int min, int max, int val, CfgId id,
                            lv_obj_t **value_lbl)
{
    lv_obj_t *row = cfg_row(parent, text);
    lv_obj_t *sl = lv_slider_create(row);
    lv_slider_set_range(sl, min, max);
    lv_slider_set_value(sl, val, LV_ANIM_OFF);
    lv_obj_set_width(sl, 180);
    lv_obj_add_event_cb(sl, cfg_event, LV_EVENT_VALUE_CHANGED, (void *)(intptr_t)id);
    lv_obj_add_event_cb(sl, cfg_event, LV_EVENT_RELEASED, (void *)(intptr_t)id);
    *value_lbl = lv_label_create(row);
    lv_obj_set_width(*value_lbl, 56);
    lv_obj_set_style_text_align(*value_lbl, LV_TEXT_ALIGN_RIGHT, 0);
    return sl;
}

static int index_of_float(const float *v, int n, float x)
{
    for (int i = 0; i < n; i++)
        if (x > v[i] - 0.01f && x < v[i] + 0.01f)
            return i;
    return 0;
}

static int index_of_int(const int *v, int n, int x)
{
    for (int i = 0; i < n; i++)
        if (v[i] == x)
            return i;
    return 0;
}

#if WEB_UI

// ---------------------------------------------------------------------------
// Wi-Fi setup: scan, pick a network, type the password (full-screen panel)

enum WifiStage { WS_LIST, WS_PASS, WS_STATUS };

static lv_obj_t *wifi_panel, *wifi_list, *wifi_msg, *wifi_ta, *wifi_kb;
static lv_timer_t *wifi_timer;
static WifiStage wifi_stage;
static WebScanEntry wifi_nets[WEB_SCAN_MAX];
static int wifi_net_count;
static bool wifi_list_filled;
static char wifi_sel[33];
static bool wifi_sel_secure;
static uint32_t wifi_wait_start;

static void wifi_show_list();

static void wifi_close()
{
    if (wifi_timer) {
        lv_timer_delete(wifi_timer);
        wifi_timer = nullptr;
    }
    if (wifi_panel) {
        lv_obj_delete(wifi_panel);
        wifi_panel = nullptr;
    }
}

static void wifi_close_event(lv_event_t *) { wifi_close(); }

static lv_obj_t *wifi_button(const char *text, int x, int y, int w, int h, lv_event_cb_t cb)
{
    lv_obj_t *b = lv_button_create(wifi_panel);
    lv_obj_set_size(b, w, h);
    lv_obj_set_pos(b, x, y);
    lv_obj_t *l = lv_label_create(b);
    lv_label_set_text(l, text);
    lv_obj_center(l);
    lv_obj_add_event_cb(b, cb, LV_EVENT_CLICKED, nullptr);
    return b;
}

static void wifi_title(const char *text)
{
    lv_obj_t *t = lv_label_create(wifi_panel);
    lv_obj_set_style_text_font(t, &font_ui_16, 0);
    lv_label_set_long_mode(t, LV_LABEL_LONG_MODE_DOTS);
    lv_obj_set_width(t, 260);
    lv_obj_set_pos(t, 8, 12);
    lv_label_set_text_fmt(t, LV_SYMBOL_WIFI "  %s", text);
}

static void wifi_connect_now()
{
    const char *pass = wifi_sel_secure && wifi_ta ? lv_textarea_get_text(wifi_ta) : "";
    web_connect(wifi_sel, pass);
    wifi_stage = WS_STATUS;
    wifi_wait_start = lv_tick_get();
    lv_obj_clean(wifi_panel);
    wifi_ta = wifi_kb = nullptr;
    wifi_title(tr(S_WIFI_NETWORKS));
    wifi_msg = lv_label_create(wifi_panel);
    lv_obj_set_width(wifi_msg, LCD_H_RES - 32);
    lv_obj_set_pos(wifi_msg, 16, 80);
    lv_label_set_text_fmt(wifi_msg, tr(S_WIFI_CONNECTING), wifi_sel);
    wifi_button(tr(S_CLOSE), LCD_H_RES - 110, 8, 100, 30, wifi_close_event);
}

static void wifi_connect_event(lv_event_t *) { wifi_connect_now(); }
static void wifi_back_event(lv_event_t *) { wifi_show_list(); }

static void wifi_show_check_event(lv_event_t *e)
{
    lv_obj_t *cb = (lv_obj_t *)lv_event_get_target(e);
    lv_textarea_set_password_mode(wifi_ta, !lv_obj_has_state(cb, LV_STATE_CHECKED));
}

static void wifi_show_password()
{
    wifi_stage = WS_PASS;
    lv_obj_clean(wifi_panel);
    wifi_title(wifi_sel);
    wifi_button(tr(S_CANCEL), LCD_H_RES - 110, 8, 100, 30, wifi_back_event);

    wifi_ta = lv_textarea_create(wifi_panel);
    lv_textarea_set_one_line(wifi_ta, true);
    lv_textarea_set_password_mode(wifi_ta, true);
    lv_textarea_set_max_length(wifi_ta, 64);
    lv_textarea_set_placeholder_text(wifi_ta, tr(S_WIFI_PASSWORD));
    lv_obj_set_size(wifi_ta, 236, 36);
    lv_obj_set_pos(wifi_ta, 4, 44);

    lv_obj_t *cb = lv_checkbox_create(wifi_panel);
    lv_checkbox_set_text(cb, tr(S_WIFI_SHOW));
    lv_obj_set_pos(cb, 248, 50);
    lv_obj_add_event_cb(cb, wifi_show_check_event, LV_EVENT_VALUE_CHANGED, nullptr);

    wifi_button(tr(S_WIFI_CONNECT), LCD_H_RES - 110, 44, 106, 36, wifi_connect_event);

    wifi_kb = lv_keyboard_create(wifi_panel);
    lv_obj_set_size(wifi_kb, LCD_H_RES, LCD_V_RES - 88);
    lv_obj_set_pos(wifi_kb, 0, 88);
    lv_obj_set_style_text_font(wifi_kb, &font_ui_16, LV_PART_ITEMS);
    lv_keyboard_set_textarea(wifi_kb, wifi_ta);
    lv_obj_add_event_cb(wifi_kb, wifi_connect_event, LV_EVENT_READY, nullptr);
}

static void wifi_pick_event(lv_event_t *e)
{
    const int i = (int)(intptr_t)lv_event_get_user_data(e);
    if (i < 0 || i >= wifi_net_count)
        return;
    strlcpy(wifi_sel, wifi_nets[i].ssid, sizeof(wifi_sel));
    wifi_sel_secure = wifi_nets[i].secure;
    if (wifi_sel_secure)
        wifi_show_password();
    else
        wifi_connect_now();
}

static void wifi_scan_event(lv_event_t *) { wifi_show_list(); }

// List of networks; it fills in (wifi_poll) when the scan ends.
static void wifi_show_list()
{
    wifi_stage = WS_LIST;
    lv_obj_clean(wifi_panel);
    wifi_ta = wifi_kb = nullptr;
    wifi_title(tr(S_WIFI_NETWORKS));
    wifi_button(LV_SYMBOL_REFRESH, LCD_H_RES - 160, 8, 44, 30, wifi_scan_event);
    wifi_button(tr(S_CLOSE), LCD_H_RES - 110, 8, 100, 30, wifi_close_event);
    wifi_list = lv_list_create(wifi_panel);
    lv_obj_set_size(wifi_list, LCD_H_RES - 8, LCD_V_RES - 50);
    lv_obj_set_pos(wifi_list, 4, 46);
    lv_obj_set_style_text_font(wifi_list, &font_ui_16, 0);
    lv_list_add_text(wifi_list, tr(S_WIFI_SCANNING));
    wifi_net_count = 0;
    wifi_list_filled = false;
    web_scan_start();
}

static void wifi_fill_list(int n)
{
    wifi_net_count = n;
    wifi_list_filled = true;
    lv_obj_clean(wifi_list);
    if (n == 0)
        lv_list_add_text(wifi_list, tr(S_WIFI_NONE_FOUND));
    for (int i = 0; i < n; i++) {
        char text[64];
        snprintf(text, sizeof(text), "%s   (%d dBm)", wifi_nets[i].ssid, wifi_nets[i].rssi);
        lv_obj_t *b = lv_list_add_button(wifi_list, wifi_nets[i].secure ? LV_SYMBOL_EYE_CLOSE : LV_SYMBOL_WIFI, text);
        lv_obj_add_event_cb(b, wifi_pick_event, LV_EVENT_CLICKED, (void *)(intptr_t)i);
    }
}

static void wifi_poll(lv_timer_t *)
{
    if (wifi_stage == WS_LIST && !wifi_list_filled) {
        int n = 0;
        const int state = web_scan_result(wifi_nets, WEB_SCAN_MAX, &n);
        if (state == 2)
            wifi_fill_list(n);
        else if (state == 0)
            web_scan_start();    // the Wi-Fi was not ready yet
    } else if (wifi_stage == WS_STATUS) {
        const WebNetInfo net = web_net_info();
        if (net.connected) {
            lv_label_set_text_fmt(wifi_msg, tr(S_WIFI_CONNECTED), wifi_sel, net.ip);
        } else if (net.fail_reason) {
            const int r = net.fail_reason;
            // 2, 15, 202, 204, 205: authentication / handshake failed (wrong password)
            // 201: no access point with that name
            const bool bad_pass = r == 2 || r == 15 || r == 202 || r == 204 || r == 205;
            if (bad_pass || r == 201 || lv_tick_elaps(wifi_wait_start) > 15000)
                lv_label_set_text(wifi_msg, tr(bad_pass ? S_WIFI_BAD_PASS : r == 201 ? S_WIFI_NO_AP : S_WIFI_FAILED));
        }
    }
}

static void wifi_open_event(lv_event_t *)
{
    if (wifi_panel)
        return;
    wifi_panel = lv_obj_create(lv_layer_top());
    lv_obj_set_size(wifi_panel, LCD_H_RES, LCD_V_RES);
    lv_obj_set_pos(wifi_panel, 0, 0);
    lv_obj_set_style_radius(wifi_panel, 0, 0);
    lv_obj_set_style_border_width(wifi_panel, 0, 0);
    lv_obj_set_style_pad_all(wifi_panel, 0, 0);
    lv_obj_set_scrollable(wifi_panel, false);
    wifi_timer = lv_timer_create(wifi_poll, 400, nullptr);
    wifi_show_list();
}

#endif // WEB_UI

static void build_settings(lv_obj_t *tab)
{
    lv_obj_set_flex_flow(tab, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_row(tab, 0, 0);

    cfg_dropdown(tab, LV_SYMBOL_LIST "  Idioma / Language", "Português\nEnglish",
                 g_settings.language == LANG_EN ? 1 : 0, CFG_LANGUAGE);
    sw_cw_auto = cfg_switch(tab, tr(S_CFG_CW_AUTO), g_settings.cw_auto_tone, CFG_CW_AUTO);
    cfg_slider(tab, tr(S_CFG_CONTRAST), 15, 200, (int)(g_settings.cw_min_contrast * 10), CFG_CONTRAST,
               &lbl_contrast);
    lv_label_set_text_fmt(lbl_contrast, "%.1f", g_settings.cw_min_contrast);
    cfg_dropdown(tab, tr(S_CFG_RTTY_BAUD), "45,45 baud\n50 baud\n75 baud\n100 baud",
                 index_of_float(RTTY_BAUDS, 4, g_settings.rtty_baud), CFG_RTTY_BAUD);
    cfg_dropdown(tab, tr(S_CFG_RTTY_POL), tr(S_RTTY_POLS), g_settings.rtty_polarity, CFG_RTTY_POL);
    cfg_dropdown(tab, tr(S_CFG_FAX_LPM), "60\n90\n120\n240",
                 index_of_int(FAX_LPMS, 4, g_settings.fax_lpm), CFG_FAX_LPM);
    cfg_dropdown(tab, "FAX: IOC", "576\n288", index_of_int(FAX_IOCS, 2, g_settings.fax_ioc), CFG_FAX_IOC);
    cfg_switch(tab, tr(S_CFG_FAX_AUTO), g_settings.fax_auto, CFG_FAX_AUTO);
    cfg_switch(tab, tr(S_CFG_SSTV_ADJ), g_settings.sstv_adjust, CFG_SSTV_ADJ);
    cfg_slider(tab, tr(S_CFG_BRIGHT), 5, 100, g_settings.lcd_brightness, CFG_BRIGHT, &lbl_bright);
    lv_label_set_text_fmt(lbl_bright, "%d %%", g_settings.lcd_brightness);
#if WEB_UI
    lv_obj_t *sw = cfg_switch(tab, tr(S_CFG_WEB), g_settings.web_enabled, CFG_WEB);
    lbl_web_note = lv_label_create(lv_obj_get_parent(sw));
    lv_label_set_text(lbl_web_note, "");
    lv_obj_move_to_index(lbl_web_note, 1);
    lv_obj_t *wbtn = lv_button_create(cfg_row(tab, tr(S_WIFI_NETWORKS)));
    lv_label_set_text_fmt(lv_label_create(wbtn), LV_SYMBOL_WIFI " %s...", tr(S_WIFI_NETWORKS));
    lv_obj_add_event_cb(wbtn, wifi_open_event, LV_EVENT_CLICKED, nullptr);
    if (!g_settings.web_enabled)    // the Wi-Fi starts after the LCD, so web_net_info() is not ready yet
        lv_obj_add_state(wbtn, LV_STATE_DISABLED);
    lv_obj_t *btn = lv_button_create(cfg_row(tab, tr(S_CFG_RESTART)));
    lv_label_set_text_fmt(lv_label_create(btn), LV_SYMBOL_REFRESH " %s", tr(S_RESTART));
    lv_obj_add_event_cb(btn, restart_event, LV_EVENT_CLICKED, nullptr);
#endif
    lbl_cfg_info = lv_label_create(tab);
    lv_obj_set_width(lbl_cfg_info, lv_pct(100));
    lv_obj_set_style_text_font(lbl_cfg_info, &font_ui_12, 0);
}

static void update_cfg_info()
{
    const WebNetInfo net = web_net_info();
    const float fs = analyzer_sample_rate();
    char s[320];
    snprintf(s, sizeof(s), "Wi-Fi: %s%s\n%s: %s\n%s: %s (%s: %u)\n%s: %.0f %%   %s: %u KB   Fs: %+.0f ppm",
             !net.started ? tr(S_WIFI_OFF) : net.connected ? net.ip : tr(S_WIFI_JOINING),
             net.ap ? tr(S_WIFI_AP) : "",
             tr(S_INFO_NET), g_settings.wifi_ssid[0] ? g_settings.wifi_ssid : tr(S_NET_NONE),
             tr(S_INFO_BOOT), boot_reason_text(), tr(S_INFO_RESETS), ui_boot_resets(),
             tr(S_INFO_LOAD), ui_load() * 100.0f, tr(S_INFO_RAM), (unsigned)(esp_get_free_heap_size() / 1024),
             fs > 0.0f ? (fs / DSP_SAMPLE_RATE - 1.0f) * 1e6f : 0.0f);
    lv_label_set_text(lbl_cfg_info, s);
    // The tone may change from the waterfall or the web page.
    if (g_settings.cw_auto_tone != lv_obj_has_state(sw_cw_auto, LV_STATE_CHECKED))
        lv_obj_set_state(sw_cw_auto, LV_STATE_CHECKED, g_settings.cw_auto_tone);
}

// ---------------------------------------------------------------------------
// Status bar and the periodic update

static void update_status()
{
    last_status = ui_get_status();
    char label[64];
    translate_label(last_status.label, label, sizeof(label));
    lv_label_set_text(lbl_mode, label[0] ? label : "-");
    const WebNetInfo net = web_net_info();
    char wifi[32];
    if (!net.started)
        wifi[0] = 0;
    else if (net.connected)
        snprintf(wifi, sizeof(wifi), "  " LV_SYMBOL_WIFI " %s", net.ip);
    else if (net.ap)
        snprintf(wifi, sizeof(wifi), "  " LV_SYMBOL_WIFI " AP");
    else
        snprintf(wifi, sizeof(wifi), "  " LV_SYMBOL_WIFI " ...");
    char s[96];
    snprintf(s, sizeof(s), "%sSNR %.0f dB%s", last_status.clip ? "CLIP  " : "", last_status.snr_db, wifi);
    lv_label_set_text(lbl_info, s);
    lv_obj_set_style_text_color(lbl_info, last_status.clip ? lv_color_hex(0xff5050) : lv_color_white(), 0);
}

static void ui_timer(lv_timer_t *)
{
    static uint32_t row_seq = 0;
    static uint8_t rows[8][UI_BINS];
    static int tick = 0;
    tick++;

    const int n = ui_get_rows(row_seq, rows, 8, &row_seq);
    draw_rows(rows, n);

    if (tick % 5 == 0) {    // 250 ms
        update_status();
        update_text(text_views[0], lbl_cw_line, ta_cw);
        update_text(text_views[1], lbl_rtty_line, ta_rtty);
        update_ftx();
    }
    const uint32_t tab = lv_tabview_get_tab_active(tabview);
    if (tab == 3 && tick % 5 == 2)    // image
        render_image(false);
    if (tab == 4 && tick % 20 == 0)   // settings
        update_cfg_info();
}

// Text tab "Clear": empties that channel's text area and its RX-tab lines.
static void clear_text_event(lv_event_t *e)
{
    const int i = (int)(intptr_t)lv_event_get_user_data(e);
    TextView &tv = text_views[i];
    tv.len = 0;
    tv.tail[0] = 0;
    lv_textarea_set_text(i ? ta_rtty : ta_cw, "");
    lv_label_set_text(i ? lbl_rtty_line : lbl_cw_line, "");
}

// ---------------------------------------------------------------------------

static lv_obj_t *plain(lv_obj_t *obj)
{
    lv_obj_set_style_pad_all(obj, 0, 0);
    lv_obj_set_style_border_width(obj, 0, 0);
    lv_obj_set_style_radius(obj, 0, 0);
    lv_obj_set_scrollable(obj, false);
    return obj;
}

static lv_display_t *display;

// Creates every widget (again after a language change).
static void build_ui()
{
    lv_obj_t *scr = lv_display_get_screen_active(display);
    lv_obj_set_style_bg_color(scr, lv_color_black(), 0);
    plain(scr);

    // Status bar
    lv_obj_t *bar = plain(lv_obj_create(scr));
    lv_obj_set_size(bar, LCD_H_RES, STATUS_H);
    lv_obj_set_style_bg_color(bar, lv_color_hex(0x1c2438), 0);
    lbl_mode = lv_label_create(bar);
    lv_obj_set_width(lbl_mode, 250);
    lv_label_set_long_mode(lbl_mode, LV_LABEL_LONG_MODE_CLIP);
    lv_obj_align(lbl_mode, LV_ALIGN_LEFT_MID, 4, 0);
    lbl_info = lv_label_create(bar);
    lv_obj_align(lbl_info, LV_ALIGN_RIGHT_MID, -4, 0);
    lv_label_set_text(lbl_mode, "RX Analyzer");
    lv_label_set_text(lbl_info, "");

    tabview = lv_tabview_create(scr);
    lv_obj_set_pos(tabview, 0, STATUS_H);
    lv_obj_set_size(tabview, LCD_H_RES, LCD_V_RES - STATUS_H);
    lv_tabview_set_tab_bar_position(tabview, LV_DIR_BOTTOM);
    lv_tabview_set_tab_bar_size(tabview, TABBAR_H);
    // No swipes between tabs: taps on the waterfall must not change the tab.
    lv_obj_set_scrollable(lv_tabview_get_content(tabview), false);
    tab_rx = plain(lv_tabview_add_tab(tabview, "RX"));
    tab_text = lv_tabview_add_tab(tabview, tr(S_TAB_TEXT));
    tab_ftx = lv_tabview_add_tab(tabview, "FT8");
    tab_img = plain(lv_tabview_add_tab(tabview, tr(S_TAB_IMAGE)));
    tab_cfg = lv_tabview_add_tab(tabview, LV_SYMBOL_SETTINGS);
    lv_obj_set_style_text_font(lv_tabview_get_tab_bar(tabview), &font_ui_16, 0);

    // RX: spectrum, waterfall, last two lines of CW and RTTY text.
    spec_canvas = make_canvas(tab_rx, &spec_buf, LCD_H_RES, SPEC_H);
    wf_canvas = make_canvas(tab_rx, &wf_buf, LCD_H_RES, WF_H);
    lv_obj_set_pos(wf_canvas, 0, SPEC_H);
    for (lv_obj_t *c : { spec_canvas, wf_canvas }) {
        lv_obj_set_clickable(c, true);
        lv_obj_add_event_cb(c, spectrum_event, LV_EVENT_SHORT_CLICKED, nullptr);
        lv_obj_add_event_cb(c, spectrum_event, LV_EVENT_LONG_PRESSED, nullptr);
    }
    int y = SPEC_H + WF_H + 1;
    for (int i = 0; i < 2; i++) {
        const lv_color_t color = lv_color_hex(i ? 0xf0d060 : 0x9fe89f);
        lv_obj_t *tag = lv_label_create(tab_rx);
        lv_label_set_text(tag, i ? "RT" : "CW");
        lv_obj_set_style_text_color(tag, color, 0);
        lv_obj_set_pos(tag, 4, y + 8);
        lv_obj_t *box = plain(lv_obj_create(tab_rx));
        lv_obj_set_style_bg_opa(box, LV_OPA_TRANSP, 0);
        lv_obj_set_pos(box, TEXT_TAG_W, y);
        lv_obj_set_size(box, LCD_H_RES - TEXT_TAG_W - 2, 32);
        lv_obj_t *l = lv_label_create(box);
        lv_obj_set_style_text_font(l, &font_ui_12, 0);
        lv_obj_set_style_text_color(l, color, 0);
        lv_obj_set_width(l, lv_pct(100));
        lv_label_set_long_mode(l, LV_LABEL_LONG_MODE_WRAP);
        lv_obj_align(l, LV_ALIGN_BOTTOM_LEFT, 0, 0);
        lv_label_set_text(l, text_views[i].tail);
        (i ? lbl_rtty_line : lbl_cw_line) = l;
        y += 34;
    }

    // Text: the last TEXT_TAB_LINES lines of CW and RTTY, each with a clear button.
    lv_obj_set_flex_flow(tab_text, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_all(tab_text, 4, 0);
    lv_obj_set_style_pad_row(tab_text, 2, 0);
    for (int i = 0; i < 2; i++) {
        lv_obj_t *head = cfg_row(tab_text, i ? "RTTY" : "CW");
        lv_obj_set_style_pad_all(head, 0, 0);
        lv_obj_t *clear = lv_button_create(head);
        lv_obj_set_height(clear, 26);
        lv_obj_set_style_pad_ver(clear, 0, 0);
        lv_obj_t *cl = lv_label_create(clear);
        lv_label_set_text_fmt(cl, LV_SYMBOL_TRASH " %s", tr(S_CLEAR));
        lv_obj_center(cl);
        lv_obj_add_event_cb(clear, clear_text_event, LV_EVENT_CLICKED, (void *)(intptr_t)i);
        lv_obj_t *ta = lv_textarea_create(tab_text);
        lv_obj_set_width(ta, lv_pct(100));
        lv_obj_set_flex_grow(ta, 1);
        lv_obj_set_click_focusable(ta, false);
        lv_textarea_set_cursor_click_pos(ta, false);    // a touch only scrolls
        lv_obj_set_style_opa(ta, LV_OPA_TRANSP, LV_PART_CURSOR);
        (i ? ta_rtty : ta_cw) = ta;
    }

    // FT8 / FT4: one compact line (mode + state) over the messages, newest first.
    plain(tab_ftx);
    lv_obj_t *dd = lv_dropdown_create(tab_ftx);
    lv_dropdown_set_options(dd, tr(S_FTX_MODES));
    lv_dropdown_set_selected(dd, g_settings.ftx_mode);
    lv_obj_set_style_text_font(dd, &font_ui_12, 0);
    lv_obj_set_style_pad_ver(dd, 3, 0);
    lv_obj_set_style_pad_hor(dd, 8, 0);
    lv_obj_set_size(dd, FTX_MODE_W, FTX_BAR_H - 4);
    lv_obj_set_pos(dd, 2, 2);
    lv_obj_add_event_cb(dd, cfg_event, LV_EVENT_VALUE_CHANGED, (void *)(intptr_t)CFG_FTX_MODE);
    lbl_ftx_state = lv_label_create(tab_ftx);
    lv_obj_set_style_text_font(lbl_ftx_state, &font_ui_12, 0);
    lv_label_set_long_mode(lbl_ftx_state, LV_LABEL_LONG_MODE_DOTS);
    lv_obj_set_width(lbl_ftx_state, LCD_H_RES - FTX_MODE_W - 12);
    lv_obj_align(lbl_ftx_state, LV_ALIGN_TOP_LEFT, FTX_MODE_W + 8, (FTX_BAR_H - 15) / 2);
    lv_label_set_text(lbl_ftx_state, "");

    ftx_table = lv_table_create(tab_ftx);
    lv_obj_set_pos(ftx_table, 0, FTX_BAR_H);
    lv_obj_set_size(ftx_table, LCD_H_RES, CONTENT_H - FTX_BAR_H);
    lv_obj_set_style_pad_all(ftx_table, 0, 0);
    lv_obj_set_style_border_width(ftx_table, 0, 0);
    lv_obj_set_style_radius(ftx_table, 0, 0);
    lv_obj_set_style_text_font(ftx_table, &font_ui_12, LV_PART_ITEMS);
    lv_obj_set_style_pad_ver(ftx_table, 2, LV_PART_ITEMS);
    lv_obj_set_style_pad_hor(ftx_table, 3, LV_PART_ITEMS);
    const char *heads[] = { "UTC", "dB", "DT", "Hz", tr(S_FTX_MESSAGE) };
    static const int widths[] = { 54, 32, 38, 42, LCD_H_RES - 54 - 32 - 38 - 42 - 6 };    // 6: scrollbar
    lv_table_set_column_count(ftx_table, 5);
    for (int c = 0; c < 5; c++) {
        lv_table_set_column_width(ftx_table, c, widths[c]);
        lv_table_set_cell_value(ftx_table, 0, c, heads[c]);
    }

    // Image: the picture (tap: whole image / fit width), state and buttons.
    img_canvas = make_canvas(tab_img, &img_buf, LCD_H_RES, IMG_H);
    lv_obj_set_clickable(img_canvas, true);
    lv_obj_add_event_cb(img_canvas, image_event, LV_EVENT_SHORT_CLICKED, nullptr);
    // Bottom strip (IMG_BAR_H): state on the left, buttons on the right.
    const int bar_y = IMG_H + (IMG_BAR_H - IMG_BTN_H) / 2;
    lv_obj_t *b = lv_button_create(tab_img);
    lv_obj_set_size(b, 92, IMG_BTN_H);
    lv_obj_set_pos(b, LCD_H_RES - 4 - 92, bar_y);
    lv_obj_t *bl = lv_label_create(b);
    lv_label_set_text_fmt(bl, LV_SYMBOL_STOP " %s", tr(S_IMG_STOP));
    lv_obj_center(bl);
    lv_obj_add_event_cb(b, img_stop_event, LV_EVENT_CLICKED, nullptr);
    lv_obj_t *b2 = lv_button_create(tab_img);
    lv_obj_set_size(b2, 76, IMG_BTN_H);
    lv_obj_set_pos(b2, LCD_H_RES - 4 - 92 - 6 - 76, bar_y);
    lv_obj_t *bl2 = lv_label_create(b2);
    lv_label_set_text(bl2, LV_SYMBOL_PLAY " FAX");
    lv_obj_center(bl2);
    lv_obj_add_event_cb(b2, fax_start_event, LV_EVENT_CLICKED, nullptr);
    lbl_img_info = lv_label_create(tab_img);
    lv_obj_set_style_text_font(lbl_img_info, &font_ui_12, 0);
    lv_obj_set_width(lbl_img_info, LCD_H_RES - 4 - 92 - 6 - 76 - 12);
    lv_label_set_long_mode(lbl_img_info, LV_LABEL_LONG_MODE_DOTS);
    lv_obj_set_pos(lbl_img_info, 4, IMG_H + (IMG_BAR_H - 15) / 2);
    lv_label_set_text(lbl_img_info, tr(S_IMG_NONE));

    build_settings(tab_cfg);
}

// Language change: the widgets are made again in the new language, and the
// text, FT8 list and image are fetched again from ui_hub.
static void rebuild_ui(void *)
{
    settings_save();
    lv_obj_clean(lv_display_get_screen_active(display));
    for (TextView &tv : text_views) {
        tv.seq = 0;
        tv.len = 0;
        tv.tail[0] = 0;
    }
    ftx_count = 0;
    ftx_seq = 0;
    img_drawn_id = 0;
    build_ui();
    lv_tabview_set_active(tabview, 4, LV_ANIM_OFF);    // back in the settings
}

void lcd_ui_start()
{
    backlight_init();
    esp_lcd_panel_io_handle_t io;
    esp_lcd_panel_handle_t panel;
    panel_init(&io, &panel);
    touch_init();

    lvgl_port_cfg_t port_cfg = ESP_LVGL_PORT_INIT_CONFIG();
    port_cfg.task_priority = 3;
    port_cfg.task_affinity = LCD_TASK_CORE;
    port_cfg.task_stack = 8192;
    ESP_ERROR_CHECK(lvgl_port_init(&port_cfg));

    lvgl_port_display_cfg_t disp_cfg = {};
    disp_cfg.io_handle = io;
    disp_cfg.panel_handle = panel;
    disp_cfg.buffer_size = LCD_H_RES * 20;    // x2, DMA-capable internal RAM (scarce)
    disp_cfg.double_buffer = true;
    disp_cfg.hres = LCD_H_RES;
    disp_cfg.vres = LCD_V_RES;
    disp_cfg.monochrome = false;
    disp_cfg.color_format = LV_COLOR_FORMAT_RGB565;
    disp_cfg.rotation.swap_xy = true;       // landscape (MADCTL MV, as TFT_eSPI rotation 1)
    disp_cfg.rotation.mirror_x = false;
    disp_cfg.rotation.mirror_y = false;
    disp_cfg.flags.buff_dma = true;
    disp_cfg.flags.swap_bytes = true;       // RGB565 goes out big endian
    display = lvgl_port_add_disp(&disp_cfg);

    lvgl_port_lock(0);
    lv_indev_t *indev = lv_indev_create();
    lv_indev_set_type(indev, LV_INDEV_TYPE_POINTER);
    lv_indev_set_read_cb(indev, touch_read_cb);
    lv_indev_set_display(indev, display);
    lv_display_set_theme(display, lv_theme_default_init(display, lv_palette_main(LV_PALETTE_BLUE),
                                                        lv_palette_main(LV_PALETTE_RED), true, &font_ui_14));
    build_lut();
    build_ui();
    lv_timer_create(ui_timer, 50, nullptr);
    lvgl_port_unlock();

    backlight_set(g_settings.lcd_brightness);
    ESP_LOGI(TAG, "LCD %dx%d ST7796 + touch FT6336U, RAM interna livre %u KB", LCD_H_RES, LCD_V_RES,
             (unsigned)(heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024));
}

#else  // !LCD_UI

void lcd_ui_start() {}

#endif // LCD_UI
